### ISSUE TITLE
Say hello!

### ISSUE THREAD

**Issue by afeld** [education/teachers#1]
Hey everyone!
I'm Aidan, live in Brooklyn, and work on the GitHub education team.  I also run [a meetup](http://hackerhours.org) for people learning to code, do a [bit of teaching](https://github.com/advanced-js/syllabus), and [like to dance](http://afeld.me/prancing).

![hi](http://media.giphy.com/media/kedaHiw5n9WLK/giphy.gif)

Who are *you!?*

**Comment by hpssjellis** [comment]
Sean mentioned learning about what other people are doing with computer
science in the classroom.

So here goes; I store all my assignments on github at:

https://github.com/hpssjellis


but get the students to work on cloud 9 ( https://c9.io/  ) learning
Javascript and mobile app design (High School ) using Phonegap. See video
at:

https://www.youtube.com/watch?v=5K75wV8FybQ

A new teacher version of the video is coming soon. It is an entire computer
programming course in one repository!

I used to use https://www.nitrous.io/  but  after students have shared
their work with me cloud 9 lets me reboot their free accounts whereas with
Nitrous.io I have to know their passwords and login individually to reboot
their accounts.


I also use google docs with my android or web app
http://rocksetta.com/teacherbrowser/#myTopper to view up to 32 students
documents live. Very cool for science class group projects or just
classroom fast feedback when teaching Physics. Kind of like clickers on
steroids. A pain to setup but well worth it later.

Presently I am working on getting the amazing ($19) spark photon robotics
micro-controler at  http://spark.io   working from a regular HTML website.
See github site at

https://github.com/hpssjellis/spark-core-web-page-html-control


Also I have lots of programming videos at

https://www.youtube.com/user/keyfreemusic/videos



I could go on and on but that is enough for today. I have coded for about
40 years and taught CS for 25.

Website http://rocksetta.com/   (Ignore the strange interest in
non-standard musical notations :>)

Twitter @rocksetta

**Comment by maxgaudin** [comment]
I'm Max and I work for a non-profit out of New Orleans called [Operation Spark](http://operationspark.org/). We teach at-risk youth (16-24) how to code so they can get jobs in the tech industry. We also teach K-12 teachers so they teach software fundamentals in their classrooms. 

Our curriculum is hosted on Github and learning Git/Github is generally in the first session of our courses. We teach HTML/CSS/Javascript and use [Cloud9](https://github.com/education/teachers) so we don't have to bother with setting up local environments, students can access it from anywhere, and it's easy for them to share their code.

Coming from the background of being a software developer I am interested to learn from teachers on here and also give advice from the geeky side of things!

<img src="http://operationspark.org/img/code-all-the-things.png" alt="Code all the things!">

**Comment by hpssjellis** [comment]
You want geeky you might want to look at this.

http://rocksetta.com/spark-core-photon/

Use a basic web page to control an arduino like microcontroller from
http://spark.io

Twitter @rocksetta

**Comment by krishermans** [comment]
Hi everyone! I'm Kris, a teacher at a University College in Belgium. I will be using git for the first time in a large classroom setting. Students will be doing a project in teams of 5. Code management and collaboration will be facilitated via GitHub.

cheers,
Kris.

**Comment by ayoubrh** [comment]
Heloo;
I hope your students will enjoy it, because it's really helpfull. I used to work without git it was hard.But now it get really easy on collaboration of code and management.
RHNABRI.

Date: Fri, 30 Jan 2015 08:28:54 -0800

**Comment by pascalalfadian** [comment]
Hello everyone! I'm Pascal, a lecturer at [Universitas Katolik Parahyangan](www.unpar.ac.id), Indonesia. I have been using git+github to host my personal projects, and looking forward to make use of the same tools for my students' group projects. It seems that the _Pulse_ feature would help me a lot in grading my students, as suggested in #7.

Cheers!
Pascal

**Comment by thomasjbradley** [comment]
Hey Everyone! I’m Thomas and teach Web Development in the Graphic Design program at Algonquin College in Ottawa, Canada.

Our students use GitHub extensively for developing and hosting websites, we use Issues to help each other and for project management, we even put student portfolio websites on GitHub with custom domains.

I also use GitHub to put up all my learning materials for all the courses that I teach, also linking to YouTube where I have a whack load of screencasts cover the same topics.

Here’s the organization: https://github.com/algonquindesign

**Comment by cengique** [comment]
Hi everyone, I am Cengiz. I teach undergraduate-level software engineering at Emory University, Atlanta, GA. I make my students learn git and Github very early in the semester so that they use it for their programming projects. 

I have an educational account with Github that has 10 free private projects. I reuse these 10 slots by clearing and archiving old projects. I lecture about git/Github a few times over the semester. Here's the syllabus for the current offering of the course:
http://www.mathcs.emory.edu/~cs370000/

And here's my website which has links to previous semesters:
http://www.biology.emory.edu/research/Prinz/Cengiz/#teach

**Comment by gjorquera** [comment]
Hello everyone!

I'm Gastón. I will be a teacher for the first time, next semester I will teach a software maintenance workshop at Universidad de Chile (yeah, I'm from Chile).

I have the vision that if students practice more about being a programmer at the university (along with all the theoretical stuff that they are already learning) then that should improve the quality of the software developed in Chile.

I intend to use GitHub extensively, to host assignments and projects, as well as perform code reviews.

Cheers.

**Comment by aletocar** [comment]
Hi everyone!
I'm Alejandro, and last semester I started teaching Software Design at Universidad ORT Uruguay.
I plan to use GitHub for my students to host their assignments and work in projects together.
Cheers!

**Comment by noew** [comment]
Hi all,
I'm Noe. I am teaching a quantitative methods class to graduate students at the New School in NYC. I am learning Git myself, and would also like my students to use it for a collaborative research project.

**Comment by bhgray-hses** [comment]
Hi there,

I'm Brent -- a CS and Math teacher at Carver Engineering and Science in Philadelphia, PA, US.  We are a 7 - 12 magnet school.  I teach CS1, Web Development, Discrete Math, and APCS.  I rolled out command line git two years ago with slow success, and am excited to incorporate git and GitHub more and more for my students.  

Thanks again to the Education Team for their support -- and the account upgrade!  Good luck to everyone in their 2015 school year!

**Comment by andrewpatterson3001** [comment]
Howdy :) I'm Andrew, a former high school math teacher. I attended Dev Bootcamp to jumpstart my web development career. I'm passionate about teaching math and CS, and I'm really excited about seeing how you use Git and Github in your classrooms :+1:

**Comment by gnerkus** [comment]
Olleh there!

I'm Ifeanyi. I work @andela where I help train developers. We're looking to integrate *Classroom for Github* into our training program. I'm passionate about teaching and video games. 
![!](https://33.media.tumblr.com/e447442bd55e7da20827480e67c6dac4/tumblr_nckip5eRUZ1r3rdh2o1_500.gif)

**Comment by bmurley** [comment]
I'm Bryan. I teach journalism and digital media, and I'm hoping to train some students to use github to collaborate on journalism projects. I teach at Eastern Illinois U.

**Comment by bkimminich** [comment]
I'm Björn and I teach Java to engineering students at FH Nordakademie in Elmshorn, Germany. I started setting up my classroom orga (https://github.com/nordakademie-einfuehrung-java) and will use it during the upcoming winter semester for the first time. I guess it will be a good reality-check for GitHub's user experience in the web and desktop apps, as none of my students are supposed to know or even learn any ```git``` commands... Let's see how this turns out...
![Things not turning out so well...](http://i.imgur.com/u3lWw.gif)

**Comment by robertmorrispainter** [comment]
Hey all,

I am Rob, and I`ve been teaching English for 9 years. I am from New Zealand, resident of Brazil, moving to China. I want to integrate Github, data, and language study, for project based learning in the classroom (if they let me) and/or in a meetup/group/activist/tech/art/experiment called Free School Hackers, a non-profit, which targets free education for languages (code, data, R, Processing et al) funded by sponsors, who share similar goals, and want to grow community. I've noticed a few others here doing similar things, so that`s exciting!

**Comment by eduOS** [comment]
Glad to know you here, Rob. I'm almost doing the same thing as you
described. Since you're moving to China, I'm wondering which city you're
living in? Can you shoot me an email? 

Here is my address: fanle_2013 at 163 dot com
Thank you.

**Comment by robertmorrispainter** [comment]
Hi EduOS - I will send an email shortly. Thank you.

**Comment by jalasem** [comment]
Hi Everyone!, I am Abdulsamii Ajala, a lead Organizer and Developer at Unilorin Google Developers Group. I am passionate and I really love teaching technologies. I am joining this great group in other have good ideas of how to teach students alike and kids how to code and collaborate better using this platform. 
Thank you

**Comment by mayinghua** [comment]
Hi, Everyone. 

I am Yinghua. I am teaching Software Engineering, and also other cources. Currently, I am using Github in software engineering class, and let student work out a project in their teams. And maybe, I would start to use github also in other course like NLP. I hope in this case, this can make students more involved. 

Thanks, 
Yinghua

**Comment by julianofischer** [comment]
Hi, all.
I am Juliano Fischer Naves and I am very interested about Github for education.
I am a programming teacher at Brazil.

**Comment by Omarasifshaikh** [comment]
Hi All,
I am Omar Shaikh and I am teaching an upper division advanced C++ course at San Francisco State University. I plan to distribute starter code using Clion and setup tests using Google's GTest library. The repositories will be connected to Travis CI, where the tests from the Google Test will auto grade the assignments. Love to be a part of this community!

**Comment by ssaunier** [comment]
Hi everyone, I'm Sébastien Saunier and I live in Paris. I am CTO of @lewagon, a European coding school (you can learn more about us at [lewagon.com](https://www.lewagon.com)).

We heavily use GitHub in the class, I wrote an article a while back on [how to use git with your students](http://sebastien.saunier.me/blog/2014/04/21/practical-example-of-using-git-in-a-school.html) that you might find interesting!

**Comment by julianofischer** [comment]
very nice @ssaunier 
thank you!

**Comment by joeyfreund** [comment]
@ssaunier , nice article! 
In fact, I just recently wrote a paper (which is being considered for a conference, so it's not public at the moment) about a similar system that I built as part of our Software Engineering course at the University of Toronto. 

The point where each student works on their own fork (so that we, instructors, can update the exercises/assignment after they're published) was one of the early design decisions I've made. It is a key feature in our workflow, and one of the issues that made GitHub Classroom not suitable for our use case.

**Comment by nalasbali** [comment]
Hi, I am Nada. I would like to invite you to participate in my PhD research which is about contributing to Open Source to modernize Computer Science education. The survey will take few minutes but will be of great value to my research.
I hope you will be happy to participate by clicking on the related link to take the suitable survey & feel free to answer any number of questions (will be much help if you can answer all):

Here you are the link to the educator's survey: https://www.surveys.unsw.edu.au/f/161596/1191/
Here you are the link to the student's survey: https://www.surveys.unsw.edu.au/f/161584/5d1e/
Here you are the link to the mentor's survey: https://www.surveys.unsw.edu.au/f/161600/2b06/
Here you are the link to other expert's & professional's from the OS industry survey: https://www.surveys.unsw.edu.au/f/161607/11a8/

"Please support my PhD research by circulating this invitation and mention it to your friends to reach educators, students, mentors & other experts & professional interested in using OS for education."

Many thanks in advance,,
Nada Alasbali
PhD of Computer Science & Engineering, UNSW

**Comment by arjenpdevries** [comment]
Hey all,
I am teaching a new BSc class on Big Data at Radboud University. So far, very happy with github for education, but only just started.
Best,
Arjen P. de Vries
Radboud University, The Netherlands

**Comment by aleman** [comment]
Hi, I'm Aleman. I am teaching Data Structures at the University of Houston. 
Here I'm exploring ways to get a nicer experience for students in their programming assignments.
We already do some automated-testing in a linux box but not integrated with git yet.

**Comment by kampar** [comment]
Hi ... My Name is Muhammad Jazman, ... and I'm not a terrorist :laughing: 


I'm teaching three subjects here in [Information Systems](http://sif.uin-suska.ac.id/) department in UIN Suska, a state islamic university in Riau Province, Indonesia:

1. internet programming for 2nd year students
2. mobile application for 3rd year students
3. java mobile application

I've taught them [a gist that had been cloned by 121 students](https://gist.github.com/kampar/5d6da959041f3b8e4c78/forks), which I'm afraid github will kick me as they may think I'm abusing their free service ...

**Comment by vishaldpsn** [comment]
Hi ... everyone ...
I am Vishal Singh from Kolkata, India. 
I am teaching class 9 & 10 at Delhi Public School Newtown, Kolkata. So far, very happy with GitHub for education. We were using GitHub for sharing our projects and the source code of our classes and also teaching how to use git.  
Best,
Vishal Singh
IT Head, Teacher
Delhi Public School Newtown, Kolkata, India.

**Comment by newtonstreet** [comment]
Hello! I'm Pam Moore working in Seattle to introduce high school journalists to computer assisted reporting techniques.

**Comment by nalasbali** [comment]
Hi, 
I would like to invite you to participate in my PhD research which is about contributing to Open Source to modernize Computer Science education. The survey will take few minutes but will be of great value to my research as i need direct evidences from OS users like you, plz. 
I hope you will be happy to participate by clicking on the related link to take the suitable survey & feel free to answer any number of questions (will be much help if you can answer all):

Here you are the link to the educator's survey: https://www.surveys.unsw.edu.au/f/161596/1191/
Here you are the link to the student's survey: https://www.surveys.unsw.edu.au/f/161584/5d1e/
Here you are the link to the mentor's survey: https://www.surveys.unsw.edu.au/f/161600/2b06/

"Please support my PhD research by circulating this invitation and mention it to your friends to reach educators, students, and mentors"

Many thanks in advance,,
Nada Alasbali
PhD of Computer Science & Engineering, UNSW

**Comment by johndbritton** [comment]
Hey folks,

Thanks for participating in this experimental community. We've moved to a new home and are welcoming hundreds of technology teachers. We're hoping that the move will spur activity

Since last week there have been nearly 200 posts.

[![screen shot 2016-08-22 at 8 07 38 pm](https://cloud.githubusercontent.com/assets/123345/17865784/1f144cfe-68a4-11e6-877f-05cee5284a40.png)](https://education.github.com/forum)

Feel free to head over [meet the newcomers](https://education.github.com/forum)
