### ISSUE TITLE
A problem with namecheap domains.

### ISSUE THREAD

**Issue by 11Kilobytes** [education/teachers#25]
I am posting this here, as I have sent emails both to Github, and to Github education, and I haven't received any responses, I don't even know if the messages I have sent have been received. Anyway:

I have received the Github Student Pack, however when I try to register for a domain, I have to verify my email. 
So, I send a confirmation message to this email and click on the link therein, however I get the following message on the webpage that opens up, “Whoops an error occurred.”

If I try to make a domain without verifying my email, I get the following message:

>It appears you have already created an order, but have not validated your email yet. 
>Please click the link in your email to continue with your order.

I have emailed name cheap about this and this way the response from their support staff:

>Hello Kabelo,
>
>As we can see your email address st-011486@aas.ru is not eligible for our nc.me promo. However if >you used Github Student pack, we can advise you to contact GitHub in order to obtain a unique link to >nc.me that will override the limitation.

>If we may be of any further assistance, please let us know.

How can I obtain the namecheap domain, if I can?

**Comment by johndbritton** [comment]
@11Kilobytes The best thing to do is email `education@github.com`, we'll get back to you there as soon as possible. We've had a huge number of students sign up so it's taking us a bit longer to respond to everyone than we'd like. I appreciate your patience.
