### ISSUE TITLE
Classroom for GitHub

### ISSUE THREAD

**Issue by tarebyte** [education/teachers#34]
Hi Everyone!

I just thought I would announce it here: today we released [Classroom for GitHub](https://classroom.github.com), a tool that makes typically tedious administrative tasks (like creating repositories and managing access for large courses) simple and streamlined.

We would love for you to use it in your classes and give us feedback in order to make your experience with GitHub even better.

You can read about it [on the blog](https://github.com/blog/2055-teachers-manage-your-courses-with-classroom-for-github)

If you have any questions or comments, feel free to [open an issue](https://github.com/education/classroom/issues/new)

Thanks!

**Comment by tkraak** [comment]
That looks very promising, **great work and thanks!**

[Here](35) are some initial questions.
