### ISSUE TITLE
Classroom for GitHub Setup

### ISSUE THREAD

**Issue by tkraak** [education/teachers#35]
[Classroom for GitHub](https://classroom.github.com) looks great! Here are my first few questions:

* How is Classroom for GitHub structured? Looks like I get **one** classroom per GitHub organization and then create assignments across courses?
* How does adding starter code work? Like most teachers, I have "starter code" in a personal repo. Can that be added to an assignment?

Thanks!

**Comment by tarebyte** [comment]
@tkraak each GitHub organization is a "Classroom" and you create the assignments for each organization.

When you create an assignment you will see that these is a form that allows you to fill in your repo name
<img width="507" alt="screen shot 2015-09-22 at 15 33 42" src="https://cloud.githubusercontent.com/assets/564113/10029356/68f87ed4-613f-11e5-8aed-e9a8e38b5a61.png">

If you set that value then every time a student accepts an assignment, we make an exact copy of your repo and push it up to the students newly created repo.

The only requirement is that you have to have permission to view the repo that you are using for starter code.

**Comment by tkraak** [comment]
@tarebyte Thanks for the quick response! I'm much clearer now on how it all works.

What does the workflow look like once I give the assignment invite link out to students?

**Comment by tarebyte** [comment]
@tkraak the student will authenticate against Classroom for GitHub with their GitHub account.

For individual assignments, they will confirm that they accept the assignment, once the process has gone through they will be taken to a page that gives them the URL to their new repo.

For group assignment, they will either create a new group or join an existing one created by other team members. Then the process is the same, they will be sent to a page that shows them the repo URL.

**Comment by tkraak** [comment]
@tarebyte What's the purpose of the group? Can I as the teacher create the group? And once the student has the repo URL they are expected to add it as a remote and so they can push to it?

**Comment by tarebyte** [comment]
The idea was that a teacher can create a reusable set of teams. Then if you have different sets of teams for different assignments you can select between them.

This is the group assignment creation form.

<img width="984" alt="screen shot 2015-09-22 at 15 49 40" src="https://cloud.githubusercontent.com/assets/564113/10029728/9bb27454-6141-11e5-8f50-89398dcae19b.png">

The repo URL takes them to GitHub.com, they can clone it from the repo page to their own computers.

**Comment by tkraak** [comment]
Ok, great! I'll put this into practice and report back. Again, nice work and thanks for answering all my questions.

**Comment by tarebyte** [comment]
Not a problem!

**Comment by jmacey** [comment]
every time I try to add the starter code “Resource could not be found on GitHub.com<http://github.com>” I’m just putting in the url of the repo which is public, am I doing something wrong?

BTW the rest looks great

Jon
On 22 Sep 2015, at 20:36, Mark Tareshawty <notifications@github.com<mailto:notifications@github.com>> wrote:


@tkraak<https://github.com/tkraak> each GitHub organization is a "Classroom" and you create the assignments for each organization.

When you create an assignment you will see that these is a form that allows you to fill in your repo name
[screen shot 2015-09-22 at 15 33 42]<https://cloud.githubusercontent.com/assets/564113/10029356/68f87ed4-613f-11e5-8aed-e9a8e38b5a61.png>

If you set that value then every time a student accepts an assignment, we make an exact copy of your repo and push it up to the students newly created repo.

The only requirement is that you have to have permission to view the repo that you are using for starter code.

—
Reply to this email directly or view it on GitHub<https://github.com/education/teachers/issues/35#issuecomment-142394874>.

BU is a Disability Two Ticks Employer and has signed up to the Mindful Employer charter. Information about the accessibility of University buildings can be found on the BU DisabledGo webpages This email is intended only for the person to whom it is addressed and may contain confidential information. If you have received this email in error, please notify the sender and delete this email, which must not be copied, distributed or disclosed to any other person. Any views or opinions presented are solely those of the author and do not necessarily represent those of Bournemouth University or its subsidiary companies. Nor can any contract be formed on behalf of the University or its subsidiary companies via email.

**Comment by bomeara** [comment]
@jmacey: it's not the url, it's just user/repo. For example, for https://github.com/PhyloMeth/GetTrees, I entered ```PhyloMeth/GetTrees``` and it was fine.

**Comment by khatchad** [comment]
It it required that you have a starter repo when creating an assignment? I created an assignment without one, but I am now unsure how students will hand in assignments as the individual repos are not forked and thus students cannot issue pull requests.

**Comment by laprej** [comment]
I am curious about this, too.  Also, is it possible to use the Teacher's Pet tool with repos created from Classroom for Github?

**Comment by tarebyte** [comment]
Hi @khatchad and @laprej I'm going to link your questions over to a [Classroom issue](https://github.com/education/classroom/issues/457) so that way we can keep better track

**Comment by nikeshashar** [comment]
Hey I'm trying to setup a test assignment using classroom. We have an open source repo and I'm able to create a link but when sending out the invite I get this error : 

![image](https://cloud.githubusercontent.com/assets/7963753/15571742/814e00e6-2334-11e6-834f-c51d2c67eb19.png)

Any ideas on where I can find a guide on how to fix this ?

**Comment by johndbritton** [comment]
@nikeshashar This is a known issue, you can read about it here. If you'd like to continue the discussion please file an issue at https://github.com/education/classroom/issues/new.

**Comment by nikeshashar** [comment]
@johndbritton Thanks - was the `here` supposed to link somewhere?

**Comment by johndbritton** [comment]
@nikeshashar Sorry about that, meant to like to this issue: https://github.com/education/classroom/issues/445

**Comment by tarebyte** [comment]
Fixed in education/classroom#604
