### ISSUE TITLE
I need students to be able to keep code private and collectable by me

### ISSUE THREAD

**Issue by EmbeddedSam** [education/teachers#50]
I currently have an organisation set up EEEManchester and we have a competition during our courses we absolutely cannot have students being able to see each others code, we also need myself and other members of staff who can see what the students are up to.

Please could someone from GitHub get in touch with me about hopefully tailoring our organisation..

**Comment by EmbeddedSam** [comment]
Further information, we are talking 60 teams of 5 students all working together all private with a need for their tutors to see privately what they are getting up to.

**Comment by tarebyte** [comment]
@EmbeddedSam are the teams and repositories already setup?

If not [GitHub Classroom](https://classroom.github.com] may be a good fit for you

**Comment by joeyfreund** [comment]
Another option is to use [Gitomator](https://gitomator.github.io/)
It's still in pre-alpha, but it can already create repos, teams and set access-permissions.

See [this page](https://gitomator.github.io/docs/classroom/access-permissions), for more info on how to set access permissions.


P.S. Gitomator, unlike GitHub Classroom, is a command-line tool. If you need any help getting started with it, please let me know.

**Comment by EmbeddedSam** [comment]
@tarebyte this looks interesting, I have made a classroom but I have no idea how to invite students and split them into teams? Would they need to sign up to GitHub and I add them, then later on split them into teams?

**Comment by EmbeddedSam** [comment]
@joeyfreund that looks really interesting, However we would still need an organisation with 300 members (one for each student) we currently only have 12 members in our organisation. I asked for a discounted plan last night they said I am being upgraded to "Silver" but that still isn't enough.

**Comment by joeyfreund** [comment]
@EmbeddedSam I hope you end up using it. If you do, please provide some feedback.
As for the organization settings, unfortunately, Gitomator cannot help you with that, you will have to talk to the good folks at GitHub.

P.S. You could use Gitomator to hack a solution that uses multiple organizations (with a smaller number of users per organization). That being said, I am assuming it would be a violation of the terms of service.

**Comment by bettymakes** [comment]
Hey @EmbeddedSam :)!

Do you have a budget you can allocate towards tools and resources? Given your needs, it looks like you're right. Even on the Silver plan, you'll still need 40 more private repositories.

In fact, as of yesterday, GitHub just updated their pricing plans from paying per private repository to paying per seat (user). I'm not sure what the Silver plan covers at this point but I believe under the previous model, you get up to 20 private repos.

I would recommend reaching out to the GitHub team to see if you can request for a higher tier if you don't have a budget that can cover the remaining 40 repos.

In terms of getting up the teams set up, user permissions etc. - do you need a hand with that? Happy to shed some light on that if you need help 👍.

Good luck!

**Comment by johndbritton** [comment]
> Would they need to sign up to GitHub and I add them, then later on split them into teams?

@EmbeddedSam When you invite them, they choose from a list of teams or create a new team. You can instruct them on how to choose teams in class.

> However we would still need an organisation with 300 members (one for each student) we currently only have 12 members in our organisation.

Your organization should be eligible for unlimited free usage. Just go to your billing page to add more seats and you will see that there is no charge.

We're working on making that a bit better experience so you don't have to add the seats manually, but for now it should work. If you have any trouble specific to your account, please contact us directly: https://education.github.com/contact and we'll get you sorted.
