### ISSUE TITLE
Organization vs. Classroom vs. Owner

### ISSUE THREAD

**Issue by drewsday** [education/teachers#52]
I'm a little baffled by the setup for the GitHub classrooms.

I applied for the Student Developer Pack and got an email saying my plan was upgraded to micro. When I followed the link to set up my classroom, I had to choose an organization to associate the classroom with.  I am a member of two organizations, but neither of them are related to the classes I teach. I created a new organization for the class I will be teaching in the Fall, and granted permissions for GitHub classroom to access that organization.

When I went to set up my first assignment and tried to make it private, I get the following error:

"Cannot make this private assignment, your limit of 0 repositories has been reached. You can request a larger plan for free at https://education.github.com/discount"

This is the original link I followed to apply for the program to begin with!  So, I'm confused - I didn't realize I needed an organization to be associated with the classroom before starting the process.  What am I not understanding?

**Comment by sanicki** [comment]
@drewsday The Student Developer Pack is an academic discount for individual students. As a teacher you should have applied for an organization academic discount for your classes. Please contact us at https://education.github.com/contact for assistance and we'll get you sorted out.
