### ISSUE TITLE
Simple HTML/JS assignments via github classroom

### ISSUE THREAD

**Issue by dhowe** [education/teachers#53]
I'm trying to setup a workflow for non-programmer students in an 'intro to creative coding' class to submit simple HTML/JS assignments via Github. 

I've setup a [Github classroom](https://classroom.github.com/) and created an assignment (with private repos for each student). However, my 'simple' setup guide is already long and complex due to the constant switching between the Atom editor , Github Desktop, and the Classroom and Github web Interfaces. Can someone suggest a simple workflow for this use-case (without the cmd-line)?   

Ideally, I think, one could paste an assignment invitation into an app, clone their repo and begin editing;  then preview in a browser, commit, push, pull as needed from the editor...

**Comment by sanicki** [comment]
This forum has been depreciated. [Click here](https://education.github.community/new-topic) to create a new topic in our new GitHub Education Community instead.
